/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BatchMessageResponse
 */
public class BatchMessageResponseTest {
    private final BatchMessageResponse model = new BatchMessageResponse();

    /**
     * Model tests for BatchMessageResponse
     */
    @Test
    public void testBatchMessageResponse() {
        // TODO: test BatchMessageResponse
    }

    /**
     * Test the property 'batchid'
     */
    @Test
    public void batchidTest() {
        // TODO: test batchid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
