/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CancelledMessageResponse
 */
public class CancelledMessageResponseTest {
    private final CancelledMessageResponse model = new CancelledMessageResponse();

    /**
     * Model tests for CancelledMessageResponse
     */
    @Test
    public void testCancelledMessageResponse() {
        // TODO: test CancelledMessageResponse
    }

    /**
     * Test the property 'messageid'
     */
    @Test
    public void messageidTest() {
        // TODO: test messageid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
