/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OTPVerify
 */
public class OTPVerifyTest {
    private final OTPVerify model = new OTPVerify();

    /**
     * Model tests for OTPVerify
     */
    @Test
    public void testOTPVerify() {
        // TODO: test OTPVerify
    }

    /**
     * Test the property 'passcode'
     */
    @Test
    public void passcodeTest() {
        // TODO: test passcode
    }

}
