/*
 * The SMS Works API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SMS Message Batch
 */
@ApiModel(description = "SMS Message Batch")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-23T20:36:29.911+01:00")
public class BatchMessage {
  @SerializedName("sender")
  private String sender = null;

  @SerializedName("destinations")
  private List<String> destinations = new ArrayList<String>();

  @SerializedName("content")
  private String content = null;

  @SerializedName("schedule")
  private String schedule = null;

  public BatchMessage sender(String sender) {
    this.sender = sender;
    return this;
  }

   /**
   * The name of the sender of the message. Avoid spaces or special characters here.
   * @return sender
  **/
  @ApiModelProperty(required = true, value = "The name of the sender of the message. Avoid spaces or special characters here.")
  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }

  public BatchMessage destinations(List<String> destinations) {
    this.destinations = destinations;
    return this;
  }

  public BatchMessage addDestinationsItem(String destinationsItem) {
    this.destinations.add(destinationsItem);
    return this;
  }

   /**
   * Telephone numbers of each of the recipients
   * @return destinations
  **/
  @ApiModelProperty(required = true, value = "Telephone numbers of each of the recipients")
  public List<String> getDestinations() {
    return destinations;
  }

  public void setDestinations(List<String> destinations) {
    this.destinations = destinations;
  }

  public BatchMessage content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Message to send to the recipient
   * @return content
  **/
  @ApiModelProperty(required = true, value = "Message to send to the recipient")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public BatchMessage schedule(String schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Date-time at which to send the batch. This is only used by the batch/schedule service.
   * @return schedule
  **/
  @ApiModelProperty(required = true, value = "Date-time at which to send the batch. This is only used by the batch/schedule service.")
  public String getSchedule() {
    return schedule;
  }

  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchMessage batchMessage = (BatchMessage) o;
    return Objects.equals(this.sender, batchMessage.sender) &&
        Objects.equals(this.destinations, batchMessage.destinations) &&
        Objects.equals(this.content, batchMessage.content) &&
        Objects.equals(this.schedule, batchMessage.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sender, destinations, content, schedule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchMessage {\n");
    
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    destinations: ").append(toIndentedString(destinations)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

