/*
 * The SMS Works API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ApiKeyResponse;
import io.swagger.client.model.ExtendedErrorModel;
import io.swagger.client.model.Login;
import io.swagger.client.model.TokenResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    
    /**
     * 
     *
     * Generates an API Key/Secret pair
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void keySecretTest() throws ApiException {
        String customerid = null;
        ApiKeyResponse response = api.keySecret(customerid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Generates a Json Web Token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        Login credentials = null;
        TokenResponse response = api.login(credentials);

        // TODO: test validations
    }
    
}
