/*
 * The SMS Works API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BatchMessage;
import io.swagger.client.model.BatchMessageResponse;
import io.swagger.client.model.CancelledMessageResponse;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.ExtendedErrorModel;
import io.swagger.client.model.MessagesResponse;
import io.swagger.client.model.ScheduledBatchResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BatchMessagesApi
 */
@Ignore
public class BatchMessagesApiTest {

    private final BatchMessagesApi api = new BatchMessagesApi();

    
    /**
     * 
     *
     * Cancels a scheduled SMS message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelScheduledBatchJobTest() throws ApiException {
        String batchid = null;
        CancelledMessageResponse response = api.cancelScheduledBatchJob(batchid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieve all messages in a batch with the given batch ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBatchByIdTest() throws ApiException {
        String batchid = null;
        MessagesResponse response = api.getBatchById(batchid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Schedules a batch of SMS messages to be sent at the date-time you specify
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scheduleBatchTest() throws ApiException {
        BatchMessage smsMessage = null;
        ScheduledBatchResponse response = api.scheduleBatch(smsMessage);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Send a single SMS message to multiple recipients
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendBatchTest() throws ApiException {
        BatchMessage smsMessage = null;
        BatchMessageResponse response = api.sendBatch(smsMessage);

        // TODO: test validations
    }
    
}
