/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CancelledMessageResponse;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.ExtendedErrorModel;
import io.swagger.client.model.Message;
import io.swagger.client.model.MessageResponse;
import io.swagger.client.model.MessagesResponse;
import io.swagger.client.model.Query;
import io.swagger.client.model.ScheduledMessageResponse;
import io.swagger.client.model.SendMessageResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessagesApi
 */
@Ignore
public class MessagesApiTest {

    private final MessagesApi api = new MessagesApi();

    
    /**
     * 
     *
     * Cancels a scheduled SMS message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelScheduledJobTest() throws ApiException {
        String messageid = null;
        CancelledMessageResponse response = api.cancelScheduledJob(messageid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get unread uncoming messages matching your search criteria
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInboxMessagesTest() throws ApiException {
        Query query = null;
        MessagesResponse response = api.getInboxMessages(query);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieve a logged message by the message ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageByIdTest() throws ApiException {
        String messageid = null;
        MessageResponse response = api.getMessageById(messageid);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get messages matching your search criteria
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessagesTest() throws ApiException {
        Query query = null;
        MessagesResponse response = api.getMessages(query);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Schedules an SMS message to be sent at the date-time you specify
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scheduleMessageTest() throws ApiException {
        Message smsMessage = null;
        ScheduledMessageResponse response = api.scheduleMessage(smsMessage);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Sends an SMS message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendMessageTest() throws ApiException {
        Message smsMessage = null;
        SendMessageResponse response = api.sendMessage(smsMessage);

        // TODO: test validations
    }
    
}
