/*
 * The SMS Works API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.HelloWorldResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UtilsApi
 */
@Ignore
public class UtilsApiTest {

    private final UtilsApi api = new UtilsApi();

    
    /**
     * 
     *
     * Returns &#39;Hello&#39; to the caller
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void helloTest() throws ApiException {
        String name = null;
        HelloWorldResponse response = api.hello(name);

        // TODO: test validations
    }
    
}
