/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BatchMessage;
import org.openapitools.client.model.BatchMessageResponse;
import org.openapitools.client.model.CancelledMessageResponse;
import org.openapitools.client.model.ErrorModel;
import org.openapitools.client.model.ExtendedErrorModel;
import org.openapitools.client.model.Message;
import org.openapitools.client.model.MessageResponse;
import org.openapitools.client.model.ScheduledBatchResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BatchMessagesApi
 */
@Disabled
public class BatchMessagesApiTest {

    private final BatchMessagesApi api = new BatchMessagesApi();

    /**
     * Sends a collection of unique SMS messages. Batches may contain up to 5000 messages at a time.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchAnyPostTest() throws ApiException {
        List<Message> messages = null;
        BatchMessageResponse response = api.batchAnyPost(messages);
        // TODO: test validations
    }

    /**
     * Retrieve all messages in a batch with the given batch ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchBatchidGetTest() throws ApiException {
        String batchid = null;
        List<MessageResponse> response = api.batchBatchidGet(batchid);
        // TODO: test validations
    }

    /**
     * Schedules a batch of SMS messages to be sent at the date time you specify
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchSchedulePostTest() throws ApiException {
        BatchMessage smsMessage = null;
        ScheduledBatchResponse response = api.batchSchedulePost(smsMessage);
        // TODO: test validations
    }

    /**
     * Send a single SMS message to multiple recipients.  Batches may contain up to 5000 messages at a time.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchSendPostTest() throws ApiException {
        BatchMessage smsMessage = null;
        BatchMessageResponse response = api.batchSendPost(smsMessage);
        // TODO: test validations
    }

    /**
     * Cancels a scheduled SMS message
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchesScheduleBatchidDeleteTest() throws ApiException {
        String batchid = null;
        CancelledMessageResponse response = api.batchesScheduleBatchidDelete(batchid);
        // TODO: test validations
    }

}
