/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreditsResponse;
import org.openapitools.client.model.ErrorModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreditsApi
 */
@Disabled
public class CreditsApiTest {

    private final CreditsApi api = new CreditsApi();

    /**
     * Returns the number of credits currently available on the account
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void creditsBalanceGetTest() throws ApiException {
        CreditsResponse response = api.creditsBalanceGet();
        // TODO: test validations
    }

}
