/*
 * The SMS Works API
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorModel;
import org.openapitools.client.model.ExtendedErrorModel;
import org.openapitools.client.model.TestResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UtilsApi
 */
@Disabled
public class UtilsApiTest {

    private final UtilsApi api = new UtilsApi();

    /**
     * Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void utilsErrorsErrorcodeGetTest() throws ApiException {
        String errorcode = null;
        ExtendedErrorModel response = api.utilsErrorsErrorcodeGet(errorcode);
        // TODO: test validations
    }

    /**
     * Returns the customer ID to the caller
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void utilsTestGetTest() throws ApiException {
        TestResponse response = api.utilsTestGet();
        // TODO: test validations
    }

}
